// PLANS
export const SET_CURRENT_PLAN_RECEVIED = 'SET_CURRENT_PLAN_RECEVIED';
export const GET_PLANS_RECEIVED = 'GET_PLANS_RECEIVED';
export const GET_PLANS_ERROR = 'GET_PLANS_ERROR';

//NEW PLAN
export const INIT_PLAN = 'INIT_PLAN';
export const ADD_MEAL = 'ADD_MEAL';
export const REMOVE_MEAL = 'REMOVE_MEAL';

export const SET_NEW_PLAN_RECEIVED = 'SET_NEW_PLAN_RECEIVED';
export const CREATE_NEW_PLAN_LOAD = 'CREATE_NEW_PLAN_LOAD'; // DO POPRAWY
export const SET_NEW_PLAN_ERROR = 'SET_NEW_PLAN_ERROR';

//MEALS
export const GET_MEALS_RECEIVED = 'GET_MEALS_RECEIVED';
export const GET_MEALS_ERROR = 'GET_MEALS_ERROR';
