export const INIT_PLAN = 'INIT_PLAN';
export const ADD_MEAL = 'ADD_MEAL';
export const REMOVE_MEAL = 'REMOVE_MEAL';
export const CREATE_NEW_PLAN_INIT = 'CREATE_NEW_PLAN_INIT';
export const CREATE_NEW_PLAN_SUCCESS = 'CREATE_NEW_PLAN_SUCCESS';
export const CREATE_NEW_PLAN_FAILD = 'CREATE_NEW_PLAN_FAILD';
export const CREATE_NEW_PLAN_LOAD = 'CREATE_NEW_PLAN_LOAD';

export const SET_MEALS = 'SET_MEALS';
export const INIT_MEALS = 'INIT_MEALS';
export const FETCH_MEALS_FAILD = 'FETCH_MEALS_FAILD';
